version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: chad
      POSTGRES_DB: ai
      POSTGRES_PASSWORD: 0000
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg-isready -U chad -d ai"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
